development:
  cloud_name: <%= ENV['CLOUDINARY_NAME'] %>
  api_key: <%= ENV['CLOUDINARY_API_KEY'] %>
  api_secret: <%= ENV['CLOUDINARY_API_SECRET'] %>
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: sample
  api_key: '123456789012345'
  api_secret: abcdefgh-ijklmnopqrstuvwxyz
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: sample
  api_key: '123456789012345'
  api_secret: abcdefgh-ijklmnopqrstuvwxyz
  enhance_image_tag: true
  static_image_support: false
